name: popgen_env
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.10
  - pandas=1.5
  - jupyterlab
  - snakemake-minimal=7
  - sra-tools
  - fastqc
  - multiqc
  - fastp      # <-- NEW TOOL
  - bwa-mem2    # <-- NEW (Phase 5: Mapping)
  - samtools  # <-- NEW (Phase 5: Processing)
  - bcftools    # <-- [NEW V4.4] Our tool for Phase 6 (Variant Calling)
  - iqtree         # <-- [V5.3] Tool for Phase 8 (Tree Building)
  
  
  
 
